lib: introduce mutable_tree_map
tokiwa-software/fuzion pull request #1177
Opened 2023-02-28 10:25 UTC by maxteufel

mutable_tree_map implements a mutable map based on AVL trees.

2023-02-28 10:52 UTC, michaellilltokiwa commented on lib/Entry.fz
> +private Entry(LM type : mutate, K type : has_total_order, V type, k K, v V) ref is
probably better to choose a more specific name here: `Tree_Map_Entry`?

2023-02-28 10:52 UTC, michaellilltokiwa commented on lib/mutable_tree_map.fz
> +  type.singleton(k K, v V) mutable_tree_map LM K V is
`type.new` would be handy, similar to `map_of(K type : has_total_order, V type, kvs array (tuple K V))`

2023-03-03 16:04 UTC, fridis requested changes
Looks good. 
Just some general comments that can be implemented in separate PR: 

- we should move features from `universe` into sub-features like `adt` to reduce the noise in the global name space
- we should think about higher level abstractions early on. The Java world is going through the painful process of adding these afterwards [JEP431](https://openjdk.org/jeps/431). We have several sorted data structures already.

2023-03-13 09:05 UTC, fridis approved these changes

2023-03-13 09:05 UTC, merged