lib: remove usage of the `some` feature
tokiwa-software/fuzion pull request #1359
Opened 2023-04-17 09:29 UTC by maxteufel

2023-04-17 09:30 UTC, michaellilltokiwa approved these changes

2023-04-18 09:05 UTC, michaellilltokiwa commented
I think some was added when nesting of choices did not yet work. Seems unnecessary now.

2023-04-18 09:10 UTC, fridis requested changes
I am happy to see the uses of `some` removed. But there are still cases where one would need some, e.g., `option nil` does not work, has to be `option (some nil)`. Not sure if there are other possible uses yet.

2023-05-01 12:39 UTC, fridis approved these changes

2023-05-01 12:39 UTC, merged