Add intrinsics to read the content of a directory
tokiwa-software/fuzion pull request #1688
Opened 2023-07-05 09:05 UTC by maxteufel

~~It still needs to be checked whether this works on Windows.~~ It does.

2023-07-26 13:28 UTC, michaellilltokiwa commented
@maxteufel I think it would be good to remove intrinsic `is_null_pointer` and either let opendir return e.g. 0 on error or pass an array for more a complex result like it is done e.g. in `bind0`.

2023-07-27 06:59 UTC, fridis commented
> The problem with returning 0 on error is that there is no guarantee by C that this is not a valid pointer, pointers can also be negative so I can't use -1 either.

We can safely assume that 0 and -1 are invalid C pointers. The result of malloc is never odd, always aligned to at least 4 bytes, most likely even 8 bytes.

2024-02-26 11:19 UTC, michaellilltokiwa requested changes
Would be cool to also add a simple effect wrapping this and a test.

2024-02-26 11:19 UTC, michaellilltokiwa commented on src/dev/flang/be/c/C.java
> +       "#include <dirent.h>\n");
Since `dirent` is POSIX the code should be put in `posix.c`. Since recently there are only C-standard headers included here.

2024-02-26 11:19 UTC, michaellilltokiwa commented on lib/fuzion/sys.fz
> +  module is_null_pointer (ptr i64) i64 => intrinsic
As discussed I would like to ideally see this removed or for it to have another name since this name only makes sense for the c backend.

2024-02-26 11:50 UTC, michaellilltokiwa commented on src/dev/flang/be/c/C.java
> +       "#include <dirent.h>\n");
@maxteufel Yes, of course you have to pull out the relevant code and put it in the `posix.c/win.c`

2024-02-27 08:48 UTC, michaellilltokiwa approved these changes
Looks nice but how did you test it when all of the features are invisible outside of base-lib?

2024-02-27 08:48 UTC, michaellilltokiwa commented on src/dev/flang/be/jvm/runtime/Runtime.java
> +    var i = (Iterator<Path>)_openStreams_.get(fd);
Call to `Runtime.unsafeIntrinsic();` is missing I think?

2024-02-29 07:32 UTC, merged