lib: implement treiber-stack
tokiwa-software/fuzion pull request #1917
Opened 2023-08-28 07:41 UTC by michaellilltokiwa

https://en.wikipedia.org/wiki/Treiber_stack

2023-08-28 11:50 UTC, michaellilltokiwa commented
@maxteufel maybe you're right and it is better to put this into a module.
@fridis what is your opinion? do we need a concurrent stack in the standard library?

2023-08-29 09:02 UTC, fridis requested changes

2023-10-27 13:34 UTC, michaellilltokiwa commented
@fridis I added a new module `lock_free` and moved the stack to this module.

2023-11-09 10:29 UTC, fridis approved these changes
Fine to have this in a separate module. We will need some thought on structuring the modules, but this might be easier if we have some contents to put into that structure:-).

2023-11-09 10:29 UTC, merged