support for turning calls into compile time constants
tokiwa-software/fuzion pull request #2067
Opened 2023-10-09 16:22 UTC by michaellilltokiwa

2023-10-11 10:19 UTC, michaellilltokiwa commented on src/dev/flang/ast/AbstractCall.java
> +    var result =
Some of these may be redundant or could be relaxed.

2023-10-11 10:20 UTC, michaellilltokiwa commented on src/dev/flang/fuir/FUIR.java
> +      // NYI can we allow none universe targets in some cases?
If call has a target that is not universe, what can we do about it?

2023-10-11 10:22 UTC, michaellilltokiwa commented on src/dev/flang/fuir/analysis/dfa/DFA.java
> +          newCall(constCl, false, _universe, args, null /* new environment */, context);
This needed for the JVM backend otherwise `new0(constCl)` will not work because it has not been generated

2023-10-17 07:40 UTC, michaellilltokiwa commented on src/dev/flang/ast/AbstractFeature.java
This should better be in another PR. I believe `inherits()` to be never empty, so this ternary is useless...

2023-10-25 13:08 UTC, fridis requested changes
Very nice and clean patch compared with the big impact this has!

One case I am unsure of is this:
```
  side_effect is say "this does something!"
  point(x,y i32) : side_effect is
    as_string => "$x,$y"
  c := point 3 4
  say c
```
Does this create a constant out of `point 3 4`? If so, this might be a bug.

Some more minor comments in the code.

2023-10-25 13:08 UTC, fridis commented on src/dev/flang/fuir/analysis/dfa/DFA.java
> +        default -> newValueConst(constCl, _call, ByteBuffer.wrap(d));
I would keep the error case for `_fuir.clazzIsChoice(constCl)`.

2023-10-25 13:08 UTC, fridis commented on src/dev/flang/be/jvm/CodeGen.java
> -          yield null;
I would keep the error case for `_fuir.clazzIsChoice(constCl)`.

2023-10-25 13:08 UTC, fridis commented on src/dev/flang/ast/AbstractConstant.java
> +    return !type().isRef(); // String is ref but NYI
I do not understand this NYI comment.

2023-10-25 14:52 UTC, michaellilltokiwa commented
> Very nice and clean patch compared with the big impact this has!
> 
> One case I am unsure of is this:
> 
> ```
>   side_effect is say "this does something!"
>   point(x,y i32) : side_effect is
>     as_string => "$x,$y"
>   c := point 3 4
>   say c
> ```
> 
> Does this create a constant out of `point 3 4`? If so, this might be a bug.
> 
> Some more minor comments in the code.

I now check if the inherited features code contains only declarations.

2023-11-02 14:11 UTC, fridis approved these changes

2023-11-02 14:11 UTC, merged