be/jvm: introduce a null type that is compatible to all types
tokiwa-software/fuzion pull request #2089
Opened 2023-10-17 07:40 UTC by maxteufel

2023-10-17 09:48 UTC, fridis requested changes
Looks good. Just a suggestion to keep `sameAs` symmetric.

2023-10-17 09:48 UTC, fridis commented on src/dev/flang/be/jvm/classfile/ClassFileConstants.java
> +    }
`sameAs` should be symmetric. Better add a special case in `CodeGen.drop`: `|| jt == NULL_TYPE`.

2023-10-18 11:56 UTC, michaellilltokiwa approved these changes

2023-10-19 15:12 UTC, fridis approved these changes

2023-10-19 15:15 UTC, merged