be: replace interpreter by interpreter2
tokiwa-software/fuzion pull request #2770
Opened 2024-03-21 08:37 UTC by michaellilltokiwa

2024-03-21 20:21 UTC, fridis requested changes
This is a big step ahead!

May comments are mostly about code structure and comments that in parts is IMHO worse than in the old interpreter, but probably easy to fix. 

Also, please add an issue to add support for stack traces of a quality similar to the old interpreter. This is a feature I will miss.

2024-03-21 20:21 UTC, fridis commented on src/dev/flang/be/interpreter/Interpreter.java
> -  /*-----------------------------  statics  -----------------------------*/
I think it helps to keep the general structure of classes, in particular of large classes. So please use these separators.

2024-03-22 07:45 UTC, michaellilltokiwa commented on tests/contracts_negative/SquareRoot.fz.expected_err
> +error 1: CONTRACT FAILED: pre-condition on call to 'SquareRoot.sqrt'
Yes, I agree. Will add an issue for this.

2024-03-25 00:39 UTC, fridis approved these changes
Looks good!
Please keep an eye on the jenkins flang.dev results and fix any new issues that will arise (like missing stack traces in err output etc.). Keep an eye on the change of total time spent in the interpreter, might make sense to use `-XjavaProf` to understand what is the most performance critical part.

2024-03-25 07:57 UTC, merged