add semicolon limit for parsing lambda expressions
tokiwa-software/fuzion pull request #3501
Opened 2024-08-02 14:33 UTC by simonvonhackewitz

For parsing lambda expressions which are not enclosed in parentheses. With this the semicolon will not be parsed as part of the lambda expression.

fix #2251

2024-08-05 08:41 UTC, fridis requested changes
Nice, you seem to have understood well how the parser works. 

However, we should try to avoid specific solutions as much as possible, and your patch introduces special handling in InlineArray that IMHO should not be needed. 

The root problem, as far as I see, is that parsing lambda/block/exprs uses class Indentation, which in `startIndent` calls `endAtSpace(Integer.MAX_VALUE)`. For some reason, this seems to be called after the semicolon in `f ()->x; y`, while this should only happen when finding the indented line `b` in code like
```
  f ()->a
     b
     c
```
So, can you try to find a solution by changing class `Indentation` to disable `endAtSpace` only if we have a new, more deeply indented line?

It would be good if this could be done without `endAtSemicolon`, but that might be impossible. If `endAtSemicolon` is needed, the code you added to relax this in `Lexer.relaxLineAndSpaceLimit` should avoid the special handling in `inlineArray` etc. If it does not, we need to understand why.

Also, if `endAtSemicolon` is needed, please add this fact to the EBNF grammar comment for `Parser.actualSpace()`, which currently reads
```
actualSpace :  operatorExpr         // no white space except enclosed in { }, [ ], or ( ).
```
and should then be
```
actualSpace :  operatorExpr         // no white space or semicolon except enclosed in { }, [ ], or ( ).
```

2024-08-05 08:41 UTC, fridis commented on src/dev/flang/parser/Parser.java
> +                         while ((s == Token.t_comma || s == Token.t_semicolon || s == Token.t_semicolonLimit) && skip(s))
This should not be needed.

2024-08-05 08:41 UTC, fridis commented on src/dev/flang/parser/Parser.java
> +                             if ((s == Token.t_comma || s == Token.t_semicolon || s == Token.t_semicolonLimit) && s != sep && !reportedMixed)
dito.

2024-08-05 11:16 UTC, simonvonhackewitz commented
wow that reduced my 35 line commit to one line

2024-08-05 11:30 UTC, fridis requested changes
That is nice. 

But please update the comment for the EBNF grammar rule `actualSpace` and in relevant Lexer methods like `endAtSpace`, maybe rename some, e.g. to `endAtSpaceOrSemi`.

2024-08-07 08:13 UTC, fridis approved these changes

2024-08-07 08:13 UTC, merged