lib: add internationalization effect
tokiwa-software/fuzion pull request #3571
Opened 2024-08-16 13:52 UTC by lisaw0

Add internationalization effect to format date based on location.

- [ x ] I have read and accept the [Tokiwa Software Fuzion Contributor Agreement](https://github.com/tokiwa-software/fuzion/blob/main/CONTRIBUTOR_LICENSE_AGREEMENT.md).

2024-08-16 14:38 UTC, fridis requested changes

2024-08-16 14:38 UTC, fridis commented on lib/internationalization/ISO_handler.fz
> +public ISO_handler : int_handler is
please add the header to every file. 

also, add a small comment explaining what this file does.

2024-08-16 14:38 UTC, fridis commented on lib/internationalization/ISO_handler.fz
> +    redef date(d i32,m i32,y i32) => "{y}-{m}-{d}"
please keep one empty line before and after feature declarations and add a comment for each feature, e.g., 

```suggestion
# ISO_handler -- provides data for ISO 8601 format
#
public ISO_handler : int_handler is

    # format date using ISO formatting rules, see https://en.wikipedia.org/wiki/ISO_8601
    # 
    # ex. `date 2024 4 12` results in `2024-04-12`.
    #
    redef date(d i32,m i32,y i32) 
    => 
      "{y}-{m}-{d}"
```

2024-08-16 14:38 UTC, fridis commented on lib/internationalization/ISO_handler.fz
> +    redef date(d i32,m i32,y i32) => "{y}-{m}-{d}"
The implementation is wrong, there are no leading `0`!

2024-08-19 10:53 UTC, fridis requested changes
Looks good. 

I have added a number of smaller suggestions, mostly affecting formatting or some text formulation. 

Please fix and then this should be ready to be merged!

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/german_handler.fz
> +    # ex.`date 2024 4 12` results in `4.12.2024`.
The example is not correct, should be:
```suggestion
    # ex.`date 2024 4 12` results in `12.4.2024`.
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/american_handler.fz
> +        "{($m).pad_left("0", 2)}/{($d).pad_left("0", 2)}/{y}"
In Fuzion, the preferred syntax for a call is `f a b`, not `f(a, b)`:
```suggestion
        "{($m).pad_left "0" 2}/{($d).pad_left "0" 2}/{y}"
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/ISO_handler.fz
> +    #format date using ISO formatting rules, see https://en.wikipedia.org/wiki/ISO_8601
```suggestion
    # format date using ISO formatting rules, see https://en.wikipedia.org/wiki/ISO_8601
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/american_handler.fz
> +    #format date using the most common american formatting rules, see https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States
```suggestion
    # format date using the most common American formatting rules, see
    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/german_handler.fz
> +    #format date using the most common german formatting rules, see https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe#Germany
```suggestion
    # format date using the most common German formatting rules, see 
    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe#Germany
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/japanese_handler.fz
> +    #format date using the most common japanese formatting rules, see https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan
```suggestion
    # format date using the most common japanese formatting rules, see
    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/korean_handler.fz
> +    #format date using the most common korean formatting rules, see https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea
```suggestion
    # format date using the most common korean formatting rules, see
    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization.fz
> +# internationalization -- unit feature to group features that internationalize certain facts provided
not really a sentence. how about
```suggestion
# internationalization -- unit feature to group features related to specific 
# geographical, political, or cultural regions such formatting of dates, 
# numbers, currencies, etc.
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/int_eff.fz
> +# int_eff -- effect that provides data for internationalization
```suggestion
# int_eff -- effect that provides operations that are specific for a geographical, political,
# or cultural region. Such operations include formatting of dates,  numbers, currencies,
# etc.
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/int_handler.fz
> +# int_handler -- provides abstract features for internationalization
```suggestion
# int_handler -- abstract handler to be used by `int_eff`
```

2024-08-19 10:53 UTC, fridis commented on lib/internationalization/ISO_handler.fz
> +    redef date(d i32,m i32,y i32)
Please add spaces after the commas, also at all other locations were feature argument lists are declared.
```suggestion
    redef date(d i32, m i32, y i32)
```

2024-08-19 12:33 UTC, lisaw0 commented on lib/internationalization/korean_handler.fz
> +    #format date using the most common korean formatting rules, see https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea
# format date using the most common Korean formatting rules, see
	    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea

2024-08-19 12:35 UTC, lisaw0 commented on lib/internationalization/japanese_handler.fz
> +    #format date using the most common japanese formatting rules, see https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan
```suggestion
    # format date using the most common Japanese formatting rules, see
	    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan
```

2024-08-19 12:41 UTC, michaellilltokiwa approved these changes

2024-08-19 12:41 UTC, michaellilltokiwa commented on lib/internationalization/korean_handler.fz
> +	    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea
```suggestion
    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_South_Korea
```

2024-08-19 12:41 UTC, michaellilltokiwa commented on lib/internationalization/japanese_handler.fz
> +	    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan
```suggestion
    # https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan
```

2024-08-19 12:41 UTC, michaellilltokiwa commented on lib/internationalization.fz
> +# geographical, political, or cultural regions such formatting of dates,
```suggestion
# geographical, political, or cultural regions such as formatting of dates, 
```

2024-08-19 13:41 UTC, fridis approved these changes

2024-08-20 08:01 UTC, merged