lib: add simpletests for internationalization effect
tokiwa-software/fuzion pull request #3627
Opened 2024-08-22 13:36 UTC by lisaw0

add one simpletest that formates manually after Japanese-format and one with default effect

- [x] I have read and accept the [Tokiwa Software Fuzion Contributor Agreement](https://github.com/tokiwa-software/fuzion/blob/main/CONTRIBUTOR_LICENSE_AGREEMENT.md).

2024-08-22 13:41 UTC, michaellilltokiwa commented on tests/i18n_default_test/i18n_default_test.fz
> +#  Source code of Fuzion test i18n_default_test2
```suggestion
#  Source code of Fuzion test i18n_default_test
```

2024-08-23 09:37 UTC, lisaw0 commented on tests/i18n_test/i18n_test.fz
> +        say "{internationalization.provide.env.date (30) (5) (2024)}"Z
```suggestion
        say "{internationalization.provide.env.date (30) (5) (2024)}"
```

2024-08-23 10:20 UTC, simonvonhackewitz requested changes

2024-08-23 10:20 UTC, simonvonhackewitz commented on tests/i18n_default_test/i18n_default_test.fz
> +    main
```suggestion
    h : envir.Vars_Handler is
      redef get(v String) option String => "de_DE.UTF-8"

    (envir.vars h).instate_self ()->

        #formates given date after default-setting, in this case German-format
        main ! internationalization.provide =>
            say "{internationalization.provide.current.date (30) (5) (2024)}"

        main
```

This uses a handler for the env.vars effect that returns always `de_DE.UTF-8`

2024-08-23 10:20 UTC, simonvonhackewitz commented on tests/i18n_default_test/Makefile
> +export LANG=de_DE.UTF-8
```suggestion
```

This is not necessary then.

2024-08-23 11:38 UTC, michaellilltokiwa approved these changes

2024-08-23 12:06 UTC, michaellilltokiwa approved these changes

2024-08-23 12:06 UTC, michaellilltokiwa commented on tests/i18n_default_test/i18n_default_test.fz
> +            say "{internationalization.provide.current.date (30) (5) (2024)}"
Does this work?
```suggestion
            say "{internationalization.provide.current.date 30 5 2024}"
```

2024-08-23 12:06 UTC, michaellilltokiwa commented on tests/i18n_test/i18n_test.fz
> +        say "{internationalization.provide.env.date (30) (5) (2024)}"
Does this work?
```suggestion
        say "{internationalization.provide.env.date 30 5 2024}"
```

2024-08-23 13:07 UTC, michaellilltokiwa approved these changes

2024-08-23 13:07 UTC, merged