lib: Add currency to internationalization and fix small mistakes
tokiwa-software/fuzion pull request #3635
Opened 2024-08-23 13:17 UTC by lisaw0

expand data by adding "currency" to internationalization effect and implement commit suggestion to simpletests

- [x] I have read and accept the [Tokiwa Software Fuzion Contributor Agreement](https://github.com/tokiwa-software/fuzion/blob/main/CONTRIBUTOR_LICENSE_AGREEMENT.md).

2024-08-23 13:38 UTC, michaellilltokiwa requested changes

2024-08-23 13:38 UTC, michaellilltokiwa commented on tests/i18n_test/i18n_test.fz
> +    #formates given date and currency after Japanese-format
```suggestion
    # formats given date and currency using Japanese-format
```

2024-08-23 13:38 UTC, michaellilltokiwa commented on tests/i18n_test/i18n_test.fz
> +        say "{internationalization.provide.env.currency (300000)}"
```suggestion
        say "{internationalization.provide.env.currency 300000}"
```

2024-08-23 13:38 UTC, michaellilltokiwa commented on tests/i18n_default_test/i18n_default_test.fz
> +        say "{internationalization.provide.current.currency (300000)}"
```suggestion
        say "{internationalization.provide.current.currency 300000}"
```

2024-08-23 13:38 UTC, michaellilltokiwa commented on lib/internationalization/provide.fz
> +    #current -- opperation of the internationalization.provide effect to be able to install the default effect
```suggestion
    # current -- operation of the internationalization.provide effect to be able to install the default effect
```

2024-08-23 13:38 UTC, michaellilltokiwa commented on lib/internationalization/korean.fz
> +    # ex.`currency 300000` results in `300000₩`.
```suggestion
    # example: `currency 300000` results in `300000₩`.
```

2024-08-23 13:38 UTC, michaellilltokiwa commented on lib/internationalization/provide.fz
> +    # currency -- operation of the internationalization.provide effect and formats the currency specific to the installed location
```suggestion
    # currency -- operation of the internationalization.provide effect and 
    # formats the currency specific to the installed location
```

2024-08-23 13:51 UTC, lisaw0 commented on tests/i18n_default_test/i18n_default_test.fz
> +    main ! internationalization.provide =>
```suggestion
        main ! internationalization.provide =>
```

2024-08-23 13:51 UTC, lisaw0 commented on tests/i18n_default_test/i18n_default_test.fz
> +        say "{internationalization.provide.current.date 30 5 2024}"
```suggestion
            say "{internationalization.provide.current.date 30 5 2024}"
```

2024-08-23 13:52 UTC, lisaw0 commented on tests/i18n_default_test/i18n_default_test.fz
> +        say "{internationalization.provide.current.currency 300000}"
```suggestion
            say "{internationalization.provide.current.currency 300000}"
```

2024-08-23 13:56 UTC, lisaw0 commented on lib/internationalization/american.fz
> +        "{c}\$"
```suggestion
        "\${c}"
```

2024-08-26 08:48 UTC, michaellilltokiwa commented on lib/internationalization/german.fz
> +        "{c} €"
```suggestion
        "{c}€"
```

2024-08-26 10:06 UTC, michaellilltokiwa approved these changes

2024-08-26 10:06 UTC, merged