turn `env` into a simple call
tokiwa-software/fuzion pull request #4189
Opened 2024-11-15 11:42 UTC by michaellilltokiwa

2024-11-15 11:45 UTC, michaellilltokiwa commented
@fridis I wonder what the downsides of this approach are but can not really think of any major ones?

2024-11-21 07:40 UTC, fridis requested changes
Very nice simplification!

Only concern I have is that `get` is too generic as a name, maybe it should be called `from_env`, or even just `env` and we could get rid for the `env` keyword (in a separate PR).

2024-11-21 07:40 UTC, fridis commented on tests/effect_installed_negative/test_effect_neg.fz.expected_err
> +  use_a => _ := a.env
I think this kind of error is very confusing. The user did not call `get` anywhere.

2024-11-21 07:40 UTC, fridis commented on src/dev/flang/fuir/analysis/dfa/DFA.java
> +    });
you should either usee `Call.getEffectForce` here or remove `Call.getEffectForce` which is otherwise unused.

2024-11-22 13:19 UTC, merged