ast: remove code duplication in `AbstractFeature.typeCall` and `AbstractCall.typeCall`
tokiwa-software/fuzion pull request #4314
Opened 2024-11-27 11:39 UTC by simonvonhackewitz

fix #4297

2024-11-27 11:40 UTC, simonvonhackewitz commented
I think there should be a better solution, but I don't quite understand the code.

2024-11-28 13:34 UTC, fridis requested changes

2024-12-04 13:10 UTC, michaellilltokiwa commented on src/dev/flang/ast/AbstractCall.java
> +      var typeCallResult = (target() instanceof AbstractCall ac && !ac.isCallToOuterRef())
I think the indentation here is a bit wrong?

2024-12-09 14:32 UTC, fridis requested changes
The patch seems correct, but the code does not really get simpler. 

Can you try the following patch instead. I made no semantic changes, just refactoring after first putting the logic fo `oc` from `AbstractCall` to `typeCall` and then moving the logic for `typeParameters2` out of `typeCall` to the recursive call to `typeCall` using `map`.

```
diff --git a/src/dev/flang/ast/AbstractCall.java b/src/dev/flang/ast/AbstractCall.java
index 16d9b3ec7..eed39d497 100644
--- a/src/dev/flang/ast/AbstractCall.java
+++ b/src/dev/flang/ast/AbstractCall.java
@@ -231,21 +231,7 @@ public abstract class AbstractCall extends Expr
           }
       }
 
-    var o = calledFeature().outer();
-    Expr oc = o == null || o.isUniverse()
-      ? new Universe()
-      : (target() instanceof AbstractCall ac && !ac.isCallToOuterRef())
-      ? ac.typeCall(p, res, that)
-      : o.typeCall(p, new List<>(o.selfType(), o.generics().asActuals()), res, that);
-
-    var tf = calledFeature().cotype(res);
-
-    return new Call(p,
-                    oc,
-                    typeParameters,
-                    Expr.NO_EXPRS,
-                    tf,
-                    tf.selfType());
+    return calledFeature().typeCall(p, typeParameters, res, that, target());
   }
 
 }
diff --git a/src/dev/flang/ast/AbstractFeature.java b/src/dev/flang/ast/AbstractFeature.java
index cfab7c9f4..92da4a6b1 100644
--- a/src/dev/flang/ast/AbstractFeature.java
+++ b/src/dev/flang/ast/AbstractFeature.java
@@ -806,25 +806,24 @@ public abstract class AbstractFeature extends Expr implements Comparable<Abstrac
    *
    * @param that the original feature that is used to lookup types.
    *
+   * @param target the target of this typeCall, null for recursive calls for
+   * outer typeCalls of to this method.
+   *
    * @return instance of Call to be used for the parent call in cotype().
    */
-  Call typeCall(SourcePosition p, List<AbstractType> typeParameters, Resolution res, AbstractFeature that)
+  Call typeCall(SourcePosition p, List<AbstractType> typeParameters, Resolution res, AbstractFeature that, Expr target)
   {
     var o = outer();
-    var oc = o == null || o.isUniverse()
-      ? new Universe()
-      : outer().typeCall(p, new List<>(o.selfType(), o.generics().asActuals()), res, that);
+    var oc = o == null || o.isUniverse()                            ? new Universe()
+      : target instanceof AbstractCall ac && !ac.isCallToOuterRef() ? ac.typeCall(p, res, that)
+      : o.typeCall(p, new List<>(o.selfType(),
+                                 o.generics().asActuals().map(that::rebaseTypeForCotype)),
+                   res, that, null);
+
     var tf = cotype(res);
-    var typeParameters2 = new List<AbstractType>();
-    for (var tp : typeParameters)
-      {
-        typeParameters2.add(typeParameters2.size() == 0
-                              ? tp
-                              : that.rebaseTypeForCotype(tp));
-      }
     return new Call(p,
                     oc,
-                    typeParameters2,
+                    typeParameters,
                     Expr.NO_EXPRS,
                     tf,
                     tf.selfType());
```

2024-12-09 21:15 UTC, michaellilltokiwa approved these changes

2024-12-09 21:15 UTC, merged